# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.localhost	TRUE	/	FALSE	1810882420	zitadel.useragent	MTc3OTM0NjQyMHx2T2FULWNtcUpheG94bEw3QlpoU3BLaVZWT2ZqZUZ2bENUY21sX2dyREZlemtqdnAzb3A0U3A3SWVyU241c09jdW05UkZPOElqWG4zQ1BQZVpIQzBQRVNySEpBOUJRPT18oXGNyFqhy_s6EQ1UVacWTghO4nByA2bTWbWwINuSrkk=
