package template

// Default templates are embedded plain strings (not //go:embed files)
// because they're small enough to live inline and substitution markers
// reading inline keep maintenance simpler than a separate .tmpl file.

// defaultClashYAML targets Mihomo (the actively-maintained Clash fork)
// and works in Clash Verge / ClashX Meta. The marker comments
// `# >>> rule-section >>>` ... `# <<< rule-section <<<` let
// applyClashKnobs strip the entire ruleset when
// rule_providers_enabled=false.
//
// Placeholders:
//   ${proxy_groups}  — replaced via applyClashKnobs before substitution
//   ${proxies}       — list of clashNode maps, indented under proxies:
//   ${proxy_names}   — comma-joined node names (for group .proxies arrays)
const defaultClashYAML = `# Mihomo / Clash full config — generated by 3xui-dashboard.
# Override this template via the clash_template_yaml admin setting.

mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback:
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN

proxies:
${proxies}

${proxy_groups}

# >>> rule-section >>>
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,节点选择
  - RULE-SET,proxy,节点选择
  - RULE-SET,direct,DIRECT
  - RULE-SET,tld-not-cn,节点选择
  - RULE-SET,gfw,节点选择
  - RULE-SET,telegramcidr,节点选择
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,applications,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,节点选择
# <<< rule-section <<<
`

// emptyClashYAML is what we return when a user has zero provisioned
// clients. Parseable, usable as a no-op Clash config (everything
// DIRECT).
const emptyClashYAML = `mixed-port: 7890
mode: rule
log-level: info
proxies: []
proxy-groups:
  - name: 节点选择
    type: select
    proxies: [DIRECT]
rules:
  - MATCH,节点选择
`

// emptySingBoxJSON — minimal sing-box config for the no-clients case.
const emptySingBoxJSON = `{
  "log": {"level": "info"},
  "outbounds": [
    {"type": "direct", "tag": "direct"},
    {"type": "block",  "tag": "block"},
    {"type": "dns",    "tag": "dns-out"}
  ],
  "route": {"final": "direct"}
}
`

// defaultSingBoxJSON targets sing-box ≥ 1.8. Placeholders:
//   ${proxies}      — comma-separated outbound JSON objects
//   ${proxy_names}  — JSON-formatted name list (without brackets)
const defaultSingBoxJSON = `{
  "log": {"level": "info", "timestamp": true},
  "dns": {
    "servers": [
      {"tag": "google",  "address": "https://dns.google/dns-query", "detour": "select"},
      {"tag": "local",   "address": "https://223.5.5.5/dns-query",  "detour": "direct"}
    ],
    "rules": [
      {"rule_set": ["geosite-cn"], "server": "local"}
    ],
    "strategy": "prefer_ipv4"
  },
  "inbounds": [
    {"type": "mixed", "tag": "mixed-in", "listen": "127.0.0.1", "listen_port": 7890}
  ],
  "outbounds": [
    {"type": "selector", "tag": "select",  "outbounds": ["auto", ${proxy_names}, "direct"], "default": "auto"},
    {"type": "urltest",  "tag": "auto",    "outbounds": [${proxy_names}], "url": "http://www.gstatic.com/generate_204", "interval": "5m", "tolerance": 50},
    ${proxies},
    {"type": "direct",   "tag": "direct"},
    {"type": "block",    "tag": "block"},
    {"type": "dns",      "tag": "dns-out"}
  ],
  "route": {
    "rule_set": [
      {"tag": "geosite-cn", "type": "remote", "format": "binary",
       "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs"},
      {"tag": "geoip-cn",   "type": "remote", "format": "binary",
       "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs"}
    ],
    "rules": [
      {"protocol": "dns",                              "outbound": "dns-out"},
      {"rule_set": ["geosite-cn", "geoip-cn"],         "outbound": "direct"},
      {"ip_is_private": true,                          "outbound": "direct"}
    ],
    "final": "select",
    "auto_detect_interface": true
  }
}
`
