package template

// Default templates are embedded plain strings (not //go:embed files)
// because they're small enough to live inline and substitution markers
// reading inline keep maintenance simpler than a separate .tmpl file.

// defaultClashSkeleton is the base Mihomo/Clash document. The policy
// sections (proxy-groups / rule-providers / rules) are now produced from
// a resolved subscription Profile and substituted into the placeholders
// below — they are no longer hardcoded here. An operator base override
// (clash_template_yaml) may use any of the same placeholders.
//
// Placeholders:
//   ${proxies}         — node proxy entries, indented under proxies:
//   ${proxy_groups}    — the proxy-groups: block (from the profile)
//   ${rule_providers}  — the rule-providers: block (from the profile; may be empty)
//   ${rules}           — the rules: block (from the profile)
//   ${proxy_names}     — comma-joined node names (only for operator templates)
const defaultClashSkeleton = `# Mihomo / Clash config — generated by 3xui-dashboard.
# Override this base via the clash_template_yaml admin setting; routing
# policy (groups + rules) is configured via subscription profiles.

mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback:
    - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN

proxies:
${proxies}

${proxy_groups}

${rule_providers}
${rules}
`

// emptyClashYAML is what we return when a user has zero provisioned
// clients. Parseable, usable as a no-op Clash config (everything
// DIRECT).
const emptyClashYAML = `mixed-port: 7890
mode: rule
log-level: info
proxies: []
proxy-groups:
  - name: 节点选择
    type: select
    proxies: [DIRECT]
rules:
  - MATCH,节点选择
`

// emptySingBoxJSON — minimal sing-box config for the no-clients case.
const emptySingBoxJSON = `{
  "log": {"level": "info"},
  "outbounds": [
    {"type": "direct", "tag": "direct"},
    {"type": "block",  "tag": "block"},
    {"type": "dns",    "tag": "dns-out"}
  ],
  "route": {"final": "direct"}
}
`

// defaultSingBoxJSON targets sing-box ≥ 1.8. Placeholders:
//   ${proxies}      — comma-separated outbound JSON objects
//   ${proxy_names}  — JSON-formatted name list (without brackets)
const defaultSingBoxJSON = `{
  "log": {"level": "info", "timestamp": true},
  "dns": {
    "servers": [
      {"tag": "google",  "address": "https://dns.google/dns-query", "detour": "select"},
      {"tag": "local",   "address": "https://223.5.5.5/dns-query",  "detour": "direct"}
    ],
    "rules": [
      {"rule_set": ["geosite-cn"], "server": "local"}
    ],
    "strategy": "prefer_ipv4"
  },
  "inbounds": [
    {"type": "mixed", "tag": "mixed-in", "listen": "127.0.0.1", "listen_port": 7890}
  ],
  "outbounds": [
    {"type": "selector", "tag": "select",  "outbounds": ["auto", ${proxy_names}, "direct"], "default": "auto"},
    {"type": "urltest",  "tag": "auto",    "outbounds": [${proxy_names}], "url": "http://www.gstatic.com/generate_204", "interval": "5m", "tolerance": 50},
    ${proxies},
    {"type": "direct",   "tag": "direct"},
    {"type": "block",    "tag": "block"},
    {"type": "dns",      "tag": "dns-out"}
  ],
  "route": {
    "rule_set": [
      {"tag": "geosite-cn", "type": "remote", "format": "binary",
       "url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs"},
      {"tag": "geoip-cn",   "type": "remote", "format": "binary",
       "url": "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs"}
    ],
    "rules": [
      {"protocol": "dns",                              "outbound": "dns-out"},
      {"rule_set": ["geosite-cn", "geoip-cn"],         "outbound": "direct"},
      {"ip_is_private": true,                          "outbound": "direct"}
    ],
    "final": "select",
    "auto_detect_interface": true
  }
}
`
