package template

import "strings"

// defaultSurgeConf is the base Surge document. The [Proxy] /
// [Proxy Group] / [Rule] sections are filled from a resolved profile.
// Surge has no separate rule-provider section — RULE-SET lines carry
// the list URL inline, so only these three placeholders are needed.
const defaultSurgeConf = `#!MANAGED-CONFIG
# Surge config — generated by 3xui-dashboard. Routing policy is
# configured via subscription profiles.

[General]
loglevel = notify
dns-server = 223.5.5.5, 119.29.29.29, system
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, localhost, *.local
ipv6 = false

[Proxy]
${proxies}

[Proxy Group]
${proxy_groups}

[Rule]
${rules}
`

// emptySurgeConf is returned when the user has no Surge-supported nodes
// (e.g. a VLESS-only fleet). Parseable, everything DIRECT.
const emptySurgeConf = `[General]
loglevel = notify

[Proxy Group]
节点选择 = select, DIRECT

[Rule]
FINAL,节点选择
`

// SurgePolicy holds the pre-rendered Surge sections (line bodies, no
// section headers — those live in the template).
type SurgePolicy struct {
	Proxies string // [Proxy] line bodies ("name = ...")
	Groups  string // [Proxy Group] lines
	Rules   string // [Rule] lines
}

// RenderSurge substitutes the Surge sections into base (or the default
// skeleton when base is empty). Surge conf has no standard Go parser, so
// there is no post-render validation; an empty proxy list short-circuits
// to a minimal DIRECT-only config. Returns ([]byte, error) for signature
// parity with RenderClash/RenderSingBox (error is always nil today).
func RenderSurge(pol SurgePolicy, base string) ([]byte, error) {
	if strings.TrimSpace(pol.Proxies) == "" && base == "" {
		return []byte(emptySurgeConf), nil
	}
	tmpl := base
	if tmpl == "" {
		tmpl = defaultSurgeConf
	}
	out := strings.ReplaceAll(tmpl, placeholderProxies, pol.Proxies)
	out = strings.ReplaceAll(out, placeholderProxyGroups, pol.Groups)
	out = strings.ReplaceAll(out, placeholderRules, pol.Rules)
	return []byte(out), nil
}
